- hosts: all
  tasks:
      - package:
             name: "httpd"
             state: present

      - copy:
           dest: "/var/www/html/index.html"
           content: "hello dolly mehra\n"

      - service:
              name: "httpd"
              state: started
              enabled: yes

      - firewalld:
              state: enabled
              port: "80/tcp"
              permanent: yes
              immediate: yes
